defaults:
  - tasks@: imagenav
  - experiments@: imagenav_rl
  - model: vc1_vitb
  - model/transform: jitter_and_shift
  - wandb_habitat@: habitat_vc
  - override hydra/output: path
  - override hydra/launcher: basic
  - _self_

RUN_TYPE: train
